name: CI/CD Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR file
        run: |
          cd DdayBack
          ./gradlew clean build
          ls build/libs  # 빌드 후 JAR 파일 확인

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -f DdayBack/Dockerfile -t yunhy96/dday:latest .
          docker push yunhy96/dday:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull yunhy96/dday:latest
            sudo docker stop dday-app || true
            sudo docker rm dday-app || true
            sudo docker run -d --name dday-app -p 8080:8080 yunhy96/dday:latest
